# Generated by Django 5.2 on 2026-05-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0002_agendamento_pagamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendamento",
            name="pagamento",
            field=models.CharField(
                choices=[("pix", "Pix"), ("cartao", "Cartão")],
                default="pix",
                max_length=20,
            ),
        ),
    ]
