# Generated by Django 5.2 on 2026-05-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0003_alter_agendamento_pagamento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agendamento",
            name="servico",
        ),
        migrations.AddField(
            model_name="agendamento",
            name="servicos",
            field=models.ManyToManyField(to="agendamentos.servico"),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="valor_total",
            field=models.FloatField(default=0),
        ),
    ]
