# Generated by Django 5.2 on 2026-05-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "agendamentos",
            "0004_remove_agendamento_servico_agendamento_servicos_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendamento",
            name="valor_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="servico",
            name="preco",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
