# Generated by Django 5.2 on 2026-05-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="pagamento",
            field=models.CharField(
                choices=[("pix", "Pix"), ("cartao", "Cartão")],
                default="pix",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
