# Generated by Django 5.2 on 2026-06-05 20:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0005_alter_agendamento_valor_total_alter_servico_preco"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agendamento",
            name="servicos",
        ),
        migrations.RemoveField(
            model_name="agendamento",
            name="data",
        ),
        migrations.AddField(
            model_name="agendamento",
            name="data_hora",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="pagamento",
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name="Servico",
        ),
    ]
